version: '3'

services:
  db:
    image: mariadb
    container_name: mibo-mariadb
    networks:
      - mibo-network
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
    restart: unless-stopped
    ports:
      - 3306:3306
  app:
    image: mibo
    build: .
    container_name: mibo
    networks:
      - mibo-network
    depends_on:
      - db
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${PWD}/.env:/opt/app/.env
    restart: unless-stopped

networks:
  mibo-network:
